""" 
The meaning of the parameters of "gen_xx_knowledge_gif" functions in the categories folder:

output_path : str
    Output path for the GIF file (including filename). e.g., "./output/animation.gif".
num_frames : int
    Total number of frames in the animation (for the full back-and-forth movement). More frames result in smoother animation but longer generation time.
duration : float
    Display time per frame in milliseconds, controlling the playback speed. Longer durations may cause stuttering playback.
camera_params_path : str or None, optional
    Path to load Open3D pinhole camera parameters. If None, the view is set automatically.
    
for more details, please refer to the documentation of the specific category.
"""

import argparse
import importlib
import pickle

no_knowledge_cat = ["Chair"]
no_instance_cat = []
no_grasp_cat = ["Chair", "Clip", "Dispenser"]


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--category", default="Bottle", type=str, help="category of objects to generate"
    )
    args = parser.parse_args()
    return args


def main():
    args = get_args()

    module = importlib.import_module(f"code.categories.{args.category}.gen_knowledge_gif")
    generate_instance_knowledge_gif = getattr(module, "generate_instance_knowledge_gif")
    if args.category not in no_grasp_cat:
        generate_grasp_knowledge_gif = getattr(module, "generate_grasp_knowledge_gif")
    if args.category not in no_knowledge_cat:
        generate_affordance_knowledge_gif = getattr(module, "generate_affordance_knowledge_gif")

    GenGifError = getattr(
        importlib.import_module(f"code.categories.{args.category}.gif_utils"),
        "GenGifError",
    )
    # please change to a pkl file generated by PROG
    pkl_path = f"./assets/conceptualizations/prog/{args.category}.pkl"
    conceptualization = pickle.load(open(pkl_path, "rb"))

    for idx, concepts in enumerate(conceptualization):
        template_names = [cc["template"] for cc in concepts]
        print(f"Processing {idx}th conceptualization with templates: {template_names}")
        idx = 0
        output_path = f"./output_gifs/{args.category.lower()}_instance_knowledge_{idx}.gif"
        try:
            # You can change the number of frames and duration as needed
            generate_instance_knowledge_gif(
                concepts,
                num_frames=40,
                duration=float(2000 / 30),
                output_path=output_path,
                camera_params_path=None,
            )
        except GenGifError as e:
            print(f"Error generating instance GIF for {idx}th conceptualization: {e}")
        except Exception as e:
            print(f"Error processing {idx}th conceptualization: {e}")


        output_path = f"./output_gifs/{args.category.lower()}_affordance_knowledge_{idx}.gif"
        try:
            if args.category not in no_knowledge_cat:
                generate_affordance_knowledge_gif(
                    concepts,
                    num_frames=40,
                    duration=float(2000 / 30),
                    output_path=output_path,
                    camera_params_path=None,
                )
        except GenGifError as e:
            print(f"Error generating affordance knowledge GIF for {idx}th conceptualization: {e}")
        except Exception as e:
            print(f"Error processing {idx}th conceptualization: {e}")


        output_path = f"./output_gifs/{args.category.lower()}_grasp_knowledge_{idx}.gif"
        try:
            if args.category not in no_grasp_cat:
                generate_grasp_knowledge_gif(
                    concepts,
                    num_frames=40,
                    duration=float(2000 / 30),
                    output_path=output_path,
                    camera_params_path=None,
                )
        except GenGifError as e:
            print(f"Error generating grasp GIF for {idx}th conceptualization: {e}")
        except Exception as e:
            print(f"Error processing {idx}th conceptualization: {e}")

if __name__ == "__main__":
    main()
